exports.ParkSmartLogsPage = class ParkSmartLogsPage {
  /**
   * @param {import('@playwright/test').Page} page
   */
  constructor(page) {
    this.page = page;
    this.summaryTab = page.getByRole('tab', { name: 'Summary' });
    this.logsTab = page.getByRole('tab', { name: 'Logs' });
    
    // Generic locators for Data Validation
    // Assumes the KPI card has a class like .kpi-card or we can filter by text "Total"
    this.totalLogsKpi = page.locator('.kpi-card, .summary-card, div').filter({ hasText: /Total Logs|Total Entries|Total Records|Count/i }).last();
    
    // Locators for Logs tab data
    // Usually pagination displays "Total: 50" or similar
    this.tableTotalRecordsText = page.getByText(/Total[:\s]+[0-9]+|Showing.*of[:\s]+[0-9]+/i);
    this.tableRows = page.getByRole('row');
  }

  async goToSummaryTab() {
    await this.summaryTab.click();
  }

  async goToLogsTab() {
    await this.logsTab.click();
  }

  async applyFilter(filterName) {
    // Sometimes it's 'Filters', sometimes 'Filters1' in the autogenerated script.
    // We'll use a more robust locator if possible, or try 'Filters' first.
    const filterButton = this.page.getByText(/^Filters\d*$/).first();
    await filterButton.click();
    await this.page.getByRole('radio', { name: filterName }).click();
    await this.page.getByRole('button', { name: 'Confirm' }).click();
    await this.page.getByRole('button', { name: 'Apply' }).click();
  }

  async clearFilters() {
    const filterButton = this.page.getByText(/^Filters\d*$/).first();
    await filterButton.click();
    await this.page.getByRole('button', { name: 'Clear All' }).click();
    await this.page.getByRole('button', { name: 'Confirm' }).click();
    await this.page.getByRole('button', { name: 'Apply' }).click();
  }

  /**
   * Helper to extract the numeric value from the Total Logs KPI
   * @returns {Promise<number>}
   */
  async getSummaryTotalCount() {
    await this.goToSummaryTab();
    // Assuming the number is in an h2, h3, or .value class inside the KPI card
    const valueLocator = this.totalLogsKpi.locator('h2, h3, .text-2xl, .value').first();
    const text = await valueLocator.textContent({ timeout: 10000 }).catch(() => "0");
    // Extract just the digits
    const match = text.match(/\d+/);
    return match ? parseInt(match[0], 10) : 0;
  }

  /**
   * Helper to extract the total number of records from the Logs table
   * It first checks if there's a pagination "Total: X" text, otherwise counts the rows (minus header).
   * @returns {Promise<number>}
   */
  async getLogsTableTotalCount() {
    await this.goToLogsTab();
    
    // Give table time to load
    await this.page.waitForTimeout(1000); 

    // Try finding a pagination total text first
    if (await this.tableTotalRecordsText.isVisible()) {
      const text = await this.tableTotalRecordsText.textContent();
      // e.g. "Total: 150" or "Showing 1-10 of 150"
      const numbers = text.match(/\d+/g);
      if (numbers && numbers.length > 0) {
         // Return the last number found (which usually represents the total in strings like "1-10 of 150")
         return parseInt(numbers[numbers.length - 1], 10);
      }
    }
    
    // Fallback: Just count the rows (assuming 1 header row)
    const count = await this.tableRows.count();
    return count > 0 ? count - 1 : 0; 
  }
};
