exports.ReportsPage = class ReportsPage {
  /**
   * @param {import('@playwright/test').Page} page
   */
  constructor(page) {
    this.page = page;
    this.reportsNavButton = page.getByRole('button', { name: 'Reports', exact: true });
    this.generateReportsLink = page.locator('a[href="/web/dashboard/GenerateReports"]');
    this.scheduleReportsLink = page.locator('a[href="/web/dashboard/ScheduleReports"]');
    
    // Locators for the reports table
    this.reportsTableRows = page.getByRole('row');
  }

  async navigateToReports() {
    await this.reportsNavButton.click();
    await this.generateReportsLink.click();
  }

  async applyFilter(filterName) {
    await this.page.getByText('Filters').click();
    await this.page.getByRole('radio', { name: filterName }).click();
    await this.page.getByRole('button', { name: 'Confirm' }).click();
    await this.page.getByRole('button', { name: 'Apply' }).click();
  }

  async clearFilters() {
    await this.page.getByText('Filters').click();
    await this.page.getByRole('button', { name: 'Clear All' }).click();
    await this.page.getByRole('button', { name: 'Confirm' }).click();
    await this.page.getByRole('button', { name: 'Apply' }).click();
  }

  async generateReport({ siteName, reportType }) {
    await this.page.getByRole('button', { name: 'Generate Report' }).first().click();
    
    if (siteName) {
      await this.page.getByRole('combobox').filter({ hasText: 'Site Name' }).click();
      await this.page.keyboard.type(siteName);
      await this.page.waitForTimeout(500); // small wait for filter to apply
      await this.page.getByRole('option', { name: siteName, exact: true }).click();
    }
    
    if (reportType) {
      await this.page.getByRole('combobox').filter({ hasText: 'Select Report Type' }).click();
      const baseName = reportType.replace(' Logs', '');
      await this.page.getByRole('option').filter({ hasText: new RegExp(baseName, 'i') }).first().click();
    }
    
    await this.page.getByRole('button', { name: 'Generate Report' }).click();
  }

  /**
   * Helper to extract the actual data from the most recently generated report in the table
   * Assumes the latest report is the first data row (index 1, after the header).
   * Note: The exact cell indices depend on the UI columns, usually:
   * [Report ID, Report Type, Site Name, Generated By, Date, Status, Action]
   */
  async getLatestReportDetails() {
    // Wait for the row to be visible and stable
    await this.page.waitForTimeout(2000); 
    const firstRow = this.reportsTableRows.nth(1);
    
    // Get text content of all cells in the row
    const cells = firstRow.getByRole('cell');
    
    // We are extracting all texts. We can return an array or an object if we assume column order.
    // Let's return raw text for robust validation.
    const rowText = await firstRow.textContent();
    
    return {
      rawText: rowText,
      rowLocator: firstRow,
      cells: cells
    };
  }
};
